# -*- coding: utf-8 -*-
"""1314 임정훈 2학기 프로그래밍 프로젝트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PdTIiLYUwMzWKhflkKhKJ_dhDUgxlXdQ

# Spam Message Identification System
### Developed by JeongHoon Lim

## Descriptions
* **Background** | 현재 우리는 정보화 시대에서 살아가며 다양한 종류의 문자를 받는다. 그 중에는 우리가 원하는 문자(ham)도 있지만, 광고성 문자 혹은 다양한 종류의 위협을 동반할 수 있는 문자인 스팸(spam) 문자가 있으며, 이는 사회적 문제로 대두되고 있다. 이에, 스팸 문자를 자동으로 판별할 수 있는 인공지능 프로그램을 구현하여 스팸 문자로 인한 사회적 문제를 해결하는 데에 조금이나마 기여해보고자 본 프로젝트를 진행하게 되었다.
* **Dataset** | [Spam Identification Dataset (Kaggle)](https://www.kaggle.com/datasets/amirdhavarshinis/spam-identification) 사용
* **Details** | 문자의 내용과 스팸문자인지의 여부가 나타난 데이터셋으로, 독립변수(문자 내용)를 학습하여 종속변수(스팸문자 여부)를 도출하는 인공지능 프로그램을 제작한다.

## Preparation

### Libraries
"""

import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from pandas import read_csv

"""### File Import"""

file_location = 'https://raw.githubusercontent.com/hoony6134/2022_programming_project_ai/main/spam.csv'
data = pd.read_csv(file_location, encoding='cp949')
data

"""## Building AI

### Variables
"""

Xlist = data[['msg']] 
Ylist = data[['spam']]
print(Xlist.shape, Ylist.shape)

"""### Model"""

X = tf.keras.layers.Input(shape=1)
Y = tf.keras.layers.Dense(1, activation='sigmoid')(X)

# Model start
model = keras.Sequential()
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(1, activation=tf.nn.relu))
# Model end

model.compile(optimizer='adam',loss='binary_crossentropy', 
              metrics='accuracy')

"""### Epoch Setting"""

epc=int(input("Epoch 값을 입력하세요: "))
model.fit(Xlist, Ylist, epochs=epc,verbose=0)
model.fit(Xlist, Ylist, epochs=10,verbose=1)